package utils

const ErrInvalidRequestQuery = "ERROR_INVALID_REQUEST_QUERY"
const ErrInvalidRequestBody = "ERROR_INVALID_REQUEST_BODY"

const ErrSettingUpdateFailed = "ERROR_SETTING_UPDATE_FAILED"

const ErrTokenVerify = "ERROR_TOKEN_VERIFY"
const ErrUnknownTokenOwner = "ERROR_UNKNOWN_TOKEN_OWNER"
const ErrNoPermission = "ERROR_NO_PERMISSION"

const ErrUnknownUser = "ERROR_UNKNOWN_USER"
const ErrProfileBoardTooShort = "ERROR_PROFILE_BOARD_TOO_SHORT"
const ErrProfileBoardTooLong = "ERROR_PROFILE_BOARD_TOO_LONG"
const ErrProfileCoverTooLarge = "ERROR_PROFILE_COVER_TOO_LARGE"
const ErrProfileCoverUploadFailed = "ERROR_PROFILE_COVER_UPLOAD_FAILED"
const ErrProfileAvatarTooLarge = "ERROR_PROFILE_AVATAR_TOO_LARGE"
const ErrProfileAvatarUploadFailed = "ERROR_PROFILE_AVATAR_UPLOAD_FAILED"
const ErrUnsupportedProfileCover = "ERROR_UNSUPPORTED_PROFILE_COVER"
const ErrUnsupportedProfileAvatar = "ERROR_UNSUPPORTED_PROFILE_AVATAR"
const ErrSelfUpdateRole = "ERROR_SELF_UPDATE_ROLE"

const ErrUnknownPost = "ERROR_UNKNOWN_POST"
const ErrPostTitleTooShort = "ERROR_POST_TITLE_TOO_SHORT"
const ErrPostTitleTooLong = "ERROR_POST_TITLE_TOO_LONG"
const ErrPostHeadlineTooLong = "ERROR_POST_HEADLINE_TOO_LONG"
const ErrPostHeadlineTooShort = "ERROR_POST_HEADLINE_TOO_SHORT"
const ErrPostContentTooLong = "ERROR_POST_CONTENT_TOO_LONG"
const ErrPostContentTooShort = "ERROR_POST_CONTENT_TOO_SHORT"
const ErrPostHashtagTooLong = "ERROR_POST_HASHTAG_TOO_LONG"
const ErrPostHashtagTooShort = "ERROR_POST_HASHTAG_TOO_SHORT"
const ErrInvalidPostHashtag = "ERROR_INVALID_POST_HASHTAG"
const ErrPostCreateFailed = "ERROR_POST_CREATE_FAILED"
const ErrPostUpdateFailed = "ERROR_POST_UPDATE_FAILED"
const ErrPostDeleteFailed = "ERROR_POST_DELETE_FAILED"
const ErrPostStatUpdateFailed = "ERROR_POST_STAT_UPDATE_FAILED"
const ErrPostHashtagListFailed = "ERROR_POST_HASHTAG_LIST_FAILED"

const ErrAttachmentTooLarge = "ERROR_ATTACHMENT_TOO_LARGE"
const ErrUnsupportedAttachment = "ERROR_UNSUPPORTED_ATTACHMENT"
const ErrAttachmentUploadFailed = "ERROR_ATTACHMENT_UPLOAD_FAILED"

const ErrUnknownEvent = "ERROR_UNKNOWN_EVENT"
const ErrEventTitleTooShort = "ERROR_EVENT_TITLE_TOO_SHORT"
const ErrEventTitleTooLong = "ERROR_EVENT_TITLE_TOO_LONG"
const ErrEventInvalidDuration = "ERROR_EVENT_INVALID_DURATION"
const ErrEventCreateFailed = "ERROR_EVENT_CREATE_FAILED"
const ErrEventUpdateFailed = "ERROR_EVENT_UPDATE_FAILED"
const ErrEventDeleteFailed = "ERROR_EVENT_DELETE_FAILED"
